### ISSUE TITLE
Checks fail when PR targets a branch other than master

### ISSUE THREAD

**Issue by ondenman** [everypolitician/ensure-regression-tests#6]
# Problem
`ensure-regression-tests` fail when the PR targets a branch other than master.

```
error: pathspec '<target-branch-name>' did not match any file(s) known to git.
```

**Comment by chrismytton** [comment]
@ondenman Have you got a link to a Travis build where this is happening?

**Comment by ondenman** [comment]
Here: https://travis-ci.org/everypolitician/wikidata_ids_decorator/jobs/215477036
